Repository flomesh-io/fsm, pull requests merged in 2023-12, with the labels that each got.

#130 refactor: extract status processor for policy attachment
  pkg/apis/policyattachment/v1alpha1/register.go
  pkg/constants/constants.go
  pkg/controllers/policyattachment/v1alpha1/accesscontrolpolicy_controller.go
  pkg/controllers/policyattachment/v1alpha1/circuitbreakingpolicy_controller.go
  pkg/controllers/policyattachment/v1alpha1/faultinjectionpolicy_controller.go
  pkg/controllers/policyattachment/v1alpha1/gatewaytlspolicy_controller.go
  pkg/controllers/policyattachment/v1alpha1/healthcheckpolicy_controller.go
  pkg/controllers/policyattachment/v1alpha1/internal.go
  pkg/controllers/policyattachment/v1alpha1/loadbalancerpolicy_controller.go
  pkg/controllers/policyattachment/v1alpha1/ratelimitpolicy_controller.go
  pkg/controllers/policyattachment/v1alpha1/retrypolicy_controller.go
  pkg/controllers/policyattachment/v1alpha1/sessionstickypolicy_controller.go
  pkg/controllers/policyattachment/v1alpha1/upstreamtlspolicy_controller.go
  pkg/controllers/policyattachment/v1alpha1/utils.go
  pkg/gateway/cache/methods.go
  pkg/gateway/cache/policies.go
  pkg/gateway/cache/types.go
  pkg/gateway/policy/status/policy_status_processor.go
  pkg/gateway/policy/status/service_policy_status_processor.go
  pkg/gateway/policy/status/types.go
  pkg/gateway/policy/status/utils.go
  pkg/gateway/types/types.go
  pkg/gateway/utils/utils.go
Labels: enhancement

#138 feat: merge HTTP/GRPC rules in case the match conditions are equal
  pkg/gateway/cache/config.go
  pkg/gateway/cache/grpcroute.go
  pkg/gateway/cache/httproute.go
  pkg/gateway/cache/tcproute.go
  pkg/gateway/cache/tlsroute.go
  pkg/gateway/cache/types.go
  pkg/gateway/cache/udproute.go
  pkg/gateway/cache/utils.go
  pkg/gateway/fgw/types.go
  pkg/gateway/policy/grpc_route_enricher.go
  pkg/gateway/policy/hostname_enricher.go
  pkg/gateway/policy/http_route_enricher.go
  pkg/gateway/policy/port_enrichers.go
  pkg/gateway/policy/service_enrichers.go
  pkg/gateway/policy/utils.go
Labels: enhancement

#141 feat: FGW supports proxy-tag plugin
  charts/fsm/README.md
  charts/fsm/components/scripts.tar.gz
  charts/fsm/components/scripts/gateways/extension/proxy-tag.js
  charts/fsm/templates/preset-mesh-config.yaml
  charts/fsm/values.schema.json
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/apis/config/v1alpha3/zz_generated.deepcopy.go
  pkg/configurator/methods.go
  pkg/configurator/mock_client_generated.go
  pkg/configurator/types.go
  pkg/gateway/cache/config.go
  pkg/gateway/fgw/types.go
  pkg/manager/listeners/client.go
Labels: enhancement

#142 fix: concurrent map iteration and writes
  docs/tests/gateway-api/README.md
  mockspec/rules
  pkg/gateway/cache/accesscontrols_trigger.go
  pkg/gateway/cache/cache.go
  pkg/gateway/cache/circuitbreakings_trigger.go
  pkg/gateway/cache/config.go
  pkg/gateway/cache/endpoints_trigger.go
  pkg/gateway/cache/endpointslices_trigger.go
  pkg/gateway/cache/faultinjection_trigger.go
  pkg/gateway/cache/gatewayclasses_trigger.go
  pkg/gateway/cache/gateways_trigger.go
  pkg/gateway/cache/gatewaytls_trigger.go
  pkg/gateway/cache/grpcroutes_trigger.go
  pkg/gateway/cache/healthchecks_trigger.go
  pkg/gateway/cache/httproutes_trigger.go
  pkg/gateway/cache/loadbalancers_trigger.go
  pkg/gateway/cache/methods.go
  pkg/gateway/cache/mock_processor_generated.go
  pkg/gateway/cache/mock_trigger_generated.go
  pkg/gateway/cache/policies.go
  pkg/gateway/cache/ratelimits_trigger.go
  pkg/gateway/cache/retries_trigger.go
  pkg/gateway/cache/secret_trigger.go
  pkg/gateway/cache/service_trigger.go
  pkg/gateway/cache/serviceimports_trigger.go
  pkg/gateway/cache/sessionstickies_trigger.go
  pkg/gateway/cache/tcproutes_trigger.go
  pkg/gateway/cache/tlsroutes_trigger.go
  pkg/gateway/cache/types.go
  pkg/gateway/cache/udproutes_trigger.go
  pkg/gateway/cache/upstreamtls_trigger.go
  pkg/gateway/cache/utils.go
Labels: bug

#144 fix: missing plugins to handle domain and route level ACL
  charts/fsm/components/scripts.tar.gz
  charts/fsm/components/scripts/gateways/config.json
  pkg/gateway/cache/types.go
Labels: bug

#147 fix: listener condition type of programmed
  pkg/gateway/utils/utils.go
Labels: bug

#146 fix: should only take care of GatewayClasses whose ControllerName is flomesh.io/gateway-controller
  pkg/controllers/gateway/v1beta1/gatewayclass_controller.go
Labels: bug

#148 fix: clean up all FSM CRDs upon uninstallation
  charts/fsm/templates/fsm-rbac.yaml
  cmd/cli/uninstall_mesh.go
Labels: bug

#151 feat: bump FGW to latest version
  charts/fsm/components/scripts.tar.gz
  charts/fsm/components/scripts/gateways/common/tls-termination.js
  charts/fsm/components/scripts/gateways/filter/header-modifier.js
  charts/fsm/components/scripts/gateways/http/fault-injection.js
  charts/fsm/components/scripts/gateways/http/metrics.js
  charts/fsm/components/scripts/gateways/http/route.js
  charts/fsm/components/scripts/gateways/http/service.js
Labels: enhancement

#129 fix: update TLS config of NamespacedIngress
  cmd/fsm-bootstrap/crds/flomesh.io_namespacedingresses.yaml
  pkg/apis/namespacedingress/v1alpha1/namespacedingress_types.go
  pkg/apis/namespacedingress/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/namespacedingress/v1alpha1/namespacedingress_controller.go
  pkg/manager/basic/http.go
  pkg/manager/basic/tls.go
  pkg/manager/listeners/announcement_handlers.go
  pkg/manager/utils/http.go
  pkg/manager/utils/tls.go
  pkg/webhook/namespacedingress/namespacedingress_webhook.go
Labels: bug

#152 feat: connector supports grpc protocol.
  pkg/connector/ctok/source.go
  pkg/connector/ktoc/source.go
  pkg/connector/ktog/gateway.go
  pkg/connector/provider/types.go
Labels: enhancement

#157 fix: inconsistency between request redirect filter script and config.json
  charts/fsm/components/scripts.tar.gz
  charts/fsm/components/scripts/gateways/filter/request-redirect.js
Labels: bug

#159 docs: update GatewayAPI compatibility [skip ci]
  docs/gateway-api-compatibility.md
Labels: documentation

#160 fix: config of RequestMirror filter
  charts/fsm/components/scripts.tar.gz
  charts/fsm/components/scripts/gateways/filter/request-mirror.js
Labels: bug

#161 refactor: optimized values.yaml
  .github/workflows/release.yml
  Makefile
  charts/fsm/README.md
  charts/fsm/templates/_helpers.tpl
  charts/fsm/templates/egress-gateway-deployment.yaml
  charts/fsm/templates/fsm-consul-connector-deployment.yaml
  charts/fsm/templates/fsm-deployment.yaml
  charts/fsm/templates/fsm-eureka-connector-deployment.yaml
  charts/fsm/templates/fsm-gateway-connector-deployment.yaml
  charts/fsm/templates/fsm-ingress-deployment.yaml
  charts/fsm/templates/fsm-injector-deployment.yaml
  charts/fsm/templates/fsm-machine-connector-deployment.yaml
  charts/fsm/templates/fsm-service.yaml
  charts/fsm/templates/grafana-deployment.yaml
  charts/fsm/templates/jaeger-deployment.yaml
  charts/fsm/templates/preset-mesh-config.yaml
  charts/fsm/templates/prometheus-deployment.yaml
  charts/fsm/values.schema.json
  charts/fsm/values.yaml
  cmd/cli/mesh_upgrade_test.go
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  demo/run-fsm-demo.sh
  dockerfiles/Dockerfile.fsm-curl
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/apis/config/v1alpha3/zz_generated.deepcopy.go
  pkg/configurator/methods.go
  pkg/configurator/methods_test.go
  pkg/connector/ctok/source.go
  pkg/connector/ktoc/source.go
  pkg/connector/provider/eureka.go
  pkg/connector/provider/types.go
  pkg/connector/types.go
  tests/e2e/e2e_retry_policy_test.go
  tests/e2e/e2e_tcp_client_server_test.go
  tests/e2e/e2e_tcp_server_first_test.go
  tests/framework/common.go
Labels: enhancement

#153 feat: FLB supports multiple modes of getting upstreams
  charts/fsm/Chart.yaml
  charts/fsm/README.md
  charts/fsm/templates/preset-mesh-config.yaml
  charts/fsm/values.yaml
  charts/gateway/Chart.yaml
  charts/gateway/README.md
  charts/gateway/values.yaml
  charts/namespaced-ingress/Chart.yaml
  charts/namespaced-ingress/README.md
  charts/namespaced-ingress/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/configurator/methods.go
  pkg/configurator/mock_client_generated.go
  pkg/configurator/types.go
  pkg/controllers/flb/service_controller.go
  pkg/controllers/servicelb/service_controller.go
  pkg/manager/listeners/client.go
  pkg/utils/ip.go
  pkg/utils/pod.go
Labels: enhancement

#162 changed fsm-curl's base image to flomesh/curl:latest
  dockerfiles/Dockerfile.fsm-curl
Labels: enhancement
