Repository flomesh-io/fsm, pull requests merged in 2023-09, with the labels that each got.

#34 fix port fordwarding script
  scripts/port-forward-all.sh
Labels: bug

#38 ci: watch branch release/v* to trigger GitHub actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/main.yml
Labels: enhancement

#35 Add SidecarTimeout to MeshConfig.
  .github/workflows/main.yml
  Makefile
  charts/fsm/README.md
  charts/fsm/templates/preset-mesh-config.yaml
  charts/fsm/values.schema.json
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha1/mesh_config.go
  pkg/apis/config/v1alpha2/mesh_config.go
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/configurator/methods.go
  pkg/configurator/mock_client_generated.go
  pkg/configurator/types.go
  pkg/manager/listeners/client.go
  pkg/messaging/broker.go
  pkg/sidecar/providers/pipy/repo/codebase/connect-tcp.js
  pkg/sidecar/providers/pipy/repo/codebase/main.js
  pkg/sidecar/providers/pipy/repo/jobs.go
  pkg/sidecar/providers/pipy/repo/policy.go
  pkg/sidecar/providers/pipy/repo/types.go
Labels: enhancement

#43 fix: regenerate CRD manifests
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
Labels: bug

#44 fix: invalid default TLS cert for ingress
  pkg/manager/utils/tls.go
Labels: bug

#45 ci: checks if CRD YAMLs are update to date
  .github/workflows/main.yml
  Makefile
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
Labels: enhancement

#47 fix: cross build fsm-interceptor image
  dockerfiles/Dockerfile.fsm-interceptor
Labels: bug

#48 feat: assign static nodePort to ingress svc only if service type is NodePort
  charts/fsm/templates/fsm-ingress-service.yaml
  charts/namespaced-ingress/templates/service.yaml
  cmd/cli/ingress_enable.go
Labels: enhancement

#49 Add RemoteLoggingLevel to MeshConfig
  charts/fsm/README.md
  charts/fsm/templates/preset-mesh-config.yaml
  charts/fsm/values.schema.json
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha1/mesh_config.go
  pkg/apis/config/v1alpha2/mesh_config.go
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/configurator/methods.go
  pkg/configurator/mock_client_generated.go
  pkg/configurator/types.go
  pkg/manager/listeners/client.go
  pkg/sidecar/providers/pipy/driver/pipy_container.go
  pkg/sidecar/providers/pipy/repo/codebase/logging.js
  pkg/sidecar/providers/pipy/repo/jobs.go
  pkg/sidecar/providers/pipy/repo/policy.go
  pkg/sidecar/providers/pipy/repo/types.go
  tests/e2e/e2e_permissive_test.go
Labels: enhancement

#55 feat: CLI checks if k8s server version meets the minimum requirements of ingress/gateway
  cmd/cli/gateway_disable.go
  cmd/cli/gateway_enable.go
  cmd/cli/ingress_disable.go
  cmd/cli/ingress_enable.go
  cmd/cli/ingress_namespaced_disable.go
  cmd/cli/ingress_namespaced_enable.go
  pkg/utils/log.go
Labels: enhancement

#57 refactor: extract constants for rendering helm chart
  cmd/cli/egressgateway_enable.go
  cmd/cli/flb_enable.go
  cmd/cli/ingress_enable.go
  cmd/cli/shared.go
  pkg/constants/constants.go
  pkg/controllers/gateway/v1beta1/gateway_controller.go
  pkg/controllers/namespacedingress/v1alpha1/namespacedingress_controller.go
Labels: enhancement

#58 build: bump pipy to 0.90.3-2
  charts/fsm/README.md
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  dockerfiles/Dockerfile.fsm-gateway
  dockerfiles/Dockerfile.fsm-ingress
  pkg/apis/config/v1alpha3/mesh_config.go
Labels: dependencies

#59 feat: enable fgw debug log if gateway log level is trace/debug
  pkg/gateway/cache/cache.go
Labels: enhancement, go

#68 fix: relocate rule level and backend level filters in config.json
  charts/fsm/components/scripts.tar.gz
  charts/fsm/components/scripts/gateways/common/health-check.js
  charts/fsm/components/scripts/gateways/common/resource-usage.js
  charts/fsm/components/scripts/gateways/filter/header-modifier.js
  charts/fsm/components/scripts/gateways/filter/request-redirect.js
  charts/fsm/components/scripts/gateways/filter/url-rewrite.js
  charts/fsm/components/scripts/gateways/http/codec.js
  charts/fsm/components/scripts/gateways/http/forward.js
  charts/fsm/components/scripts/gateways/http/route.js
  charts/fsm/components/scripts/gateways/lib/metrics.js
  charts/fsm/components/scripts/gateways/main.js
  charts/fsm/components/scripts/gateways/server/web-server.js
  pkg/gateway/cache/cache.go
  pkg/gateway/cache/cacheutils.go
  pkg/gateway/cache/types.go
  pkg/gateway/routecfg/types.go
Labels: bug, go

#72 Changed implementation of outbound per-request load balancing.
  charts/fsm/README.md
  charts/fsm/templates/preset-mesh-config.yaml
  charts/fsm/values.schema.json
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha1/mesh_config.go
  pkg/apis/config/v1alpha2/mesh_config.go
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/messaging/broker.go
  pkg/sidecar/providers/pipy/repo/codebase/modules/outbound-http-load-balancing.js
  pkg/sidecar/providers/pipy/repo/codebase/modules/outbound-http-routing.js
  pkg/sidecar/providers/pipy/repo/jobs.go
  pkg/sidecar/providers/pipy/repo/policy.go
  pkg/sidecar/providers/pipy/repo/types.go
Labels: enhancement

#73 fix: check if resource revision of svc is changed, ignore processing if it doesn't
  pkg/controllers/flb/service_controller.go
Labels: bug

#74 fix: a service is routable if it's referred by request mirror filter
  charts/fsm/README.md
  charts/gateway/README.md
  charts/namespaced-ingress/README.md
  pkg/gateway/cache/cache.go
Labels: enhancement

#75 fix: high cyclomatic complexity
  pkg/gateway/cache/cache.go
  pkg/gateway/cache/config.go
  pkg/gateway/cache/methods.go
  pkg/gateway/cache/utils.go
Labels: enhancement
