Repository flomesh-io/fsm, pull requests merged in 2024-06, with the labels that each got.

#281 chore: Update CODEOWNERS
  CODEOWNERS
Labels: documentation

#282 chore: Update OWNERS
  OWNERS
Labels: documentation

#280 fix: connector issues
  .github/workflows/main.yml
  pkg/connector/provider/eureka.go
  pkg/connector/provider/nacos.go
  pkg/sidecar/providers/pipy/repo/jobs.go
  pkg/sidecar/providers/pipy/repo/policy.go
  tests/e2e/e2e_retry_policy_test.go
Labels: bug

#283 build(deps): bump pipy to 1.2.0
  charts/fsm/README.md
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  dockerfiles/Dockerfile.fsm-gateway
  dockerfiles/Dockerfile.fsm-ingress
  docs/tests/gateway-api/README.md
  pkg/apis/config/v1alpha3/mesh_config.go
  scripts/k3d-multicluster-deploy-apps.sh
  tests/e2e/e2e_fsm_ingress_test.go
  tests/e2e/e2e_gatewayapi_test.go
Labels: enhancement

#286 fix: merge new CRD with existing CRD, not replace
  cmd/fsm-bootstrap/fsm-bootstrap.go
Labels: enhancement

#292 feat: add annotation for FLB session sticky
  pkg/constants/constants.go
  pkg/controllers/flb/service_controller.go
  pkg/controllers/flb/types.go
Labels: enhancement

#293 [security] fix: Classic builder cache poisoning
  go.mod
  go.sum
Labels: enhancement

#296 build(deps): bump github.com/hashicorp/vault to v1.16.3
  go.mod
  go.sum
Labels: enhancement
