Repository flomesh-io/fsm, pull requests merged in 2024-03, with the labels that each got.

#198 test: add e2e testcases for Gateway-API implementation
  .github/workflows/main.yml
  tests/e2e/e2e_gatewayapi_test.go
  tests/framework/common.go
  tests/framework/common_gatewayapi.go
  tests/framework/common_traffic.go
  tests/framework/types.go
Labels: enhancement

#199 test: add e2e testcases for Ingress/NamespacedIngress
  .github/workflows/main.yml
  tests/e2e/e2e_fsm_ingress_test.go
  tests/e2e/e2e_gatewayapi_test.go
  tests/e2e/e2e_namespacedingress_test.go
  tests/framework/common.go
  tests/framework/common_ingress.go
  tests/framework/types.go
Labels: enhancement

#202 build(deps): bump go from 1.21 to 1.22
  .github/workflows/codeql-analysis.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  Dockerfile
  Makefile
  go.mod
Labels: enhancement, dependencies

#203 build(deps): bump helm, controller-runtime and k8s api version
  Makefile
  cmd/fsm-bootstrap/crds/flomesh.io_namespacedingresses.yaml
  codegen/gen-crd-client.sh
  go.mod
  go.sum
  pkg/gen/client/config/informers/externalversions/factory.go
  pkg/gen/client/machine/informers/externalversions/factory.go
  pkg/gen/client/multicluster/informers/externalversions/factory.go
  pkg/gen/client/namespacedingress/informers/externalversions/factory.go
  pkg/gen/client/networking/informers/externalversions/factory.go
  pkg/gen/client/plugin/informers/externalversions/factory.go
  pkg/gen/client/policy/informers/externalversions/factory.go
  pkg/gen/client/policyattachment/informers/externalversions/factory.go
Labels: dependencies

#209 fix: check existence of TLS port in FLB service spec
  pkg/flb/utils.go
Labels: enhancement, go

#215 optimized fsm connector.
  charts/connector/README.md
  charts/connector/templates/deployment.yaml
  charts/connector/values.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_consulconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_eurekaconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_gatewayconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_machineconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_nacosconnectors.yaml
  cmd/fsm-connector/fsm-connector.go
  pkg/apis/connector/v1alpha1/consul.go
  pkg/apis/connector/v1alpha1/eureka.go
  pkg/apis/connector/v1alpha1/gateway.go
  pkg/apis/connector/v1alpha1/machine.go
  pkg/apis/connector/v1alpha1/nacos.go
  pkg/apis/connector/v1alpha1/types.go
  pkg/apis/connector/v1alpha1/zz_generated.deepcopy.go
  pkg/connector/cli/broadcast.go
  pkg/connector/cli/cache.go
  pkg/connector/cli/client.go
  pkg/connector/cli/config.go
  pkg/connector/cli/run.go
  pkg/connector/cli/sync.go
  pkg/connector/cli/types.go
  pkg/connector/controller.go
  pkg/connector/ctok/source.go
  pkg/connector/ctok/syncer.go
  pkg/connector/ctok/types.go
  pkg/connector/discovery.go
  pkg/connector/ktoc/broadcast.go
  pkg/connector/ktoc/source.go
  pkg/connector/ktoc/syncer.go
  pkg/connector/ktog/syncer.go
  pkg/connector/provider/consul.go
  pkg/connector/provider/eureka.go
  pkg/connector/provider/machine.go
  pkg/connector/provider/nacos.go
  pkg/controllers/connector/v1alpha1/types.go
  pkg/messaging/broker.go
Labels: enhancement

#216 feat: support headless service without selector
  pkg/gateway/cache/config.go
  pkg/gateway/cache/types.go
  pkg/gateway/cache/utils.go
Labels: enhancement
