Repository flomesh-io/fsm, pull requests merged in 2024-04, with the labels that each got.

#217 fix: watch Endpoints changes for headless service
  pkg/gateway/cache/cache.go
  pkg/gateway/cache/endpoints_trigger.go
  pkg/gateway/cache/methods.go
  pkg/gateway/client.go
Labels: enhancement

#218 fix: minimum k8s for fsm-ingress
  cmd/fsm-ingress/fsm-ingress.go
Labels: bug

#220 fix: add resource limit to all containers
  charts/connector/README.md
  charts/connector/templates/deployment.yaml
  charts/connector/values.schema.json
  charts/connector/values.yaml
  charts/fsm/README.md
  charts/fsm/templates/cleanup-hook.yaml
  charts/fsm/templates/fsm-deployment.yaml
  charts/fsm/templates/fsm-ingress-deployment.yaml
  charts/fsm/templates/fsm-injector-deployment.yaml
  charts/fsm/templates/preinstall-hook.yaml
  charts/fsm/values.schema.json
  charts/fsm/values.yaml
  charts/gateway/README.md
  charts/gateway/templates/deployment.yaml
  charts/gateway/values.yaml
  charts/namespaced-ingress/README.md
  charts/namespaced-ingress/templates/deployment.yaml
  charts/namespaced-ingress/values.yaml
Labels: enhancement

#221 feat: support forward mode.
  charts/fsm/README.md
  charts/fsm/values.schema.json
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_consulconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_eurekaconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_nacosconnectors.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/apis/connector/v1alpha1/consul.go
  pkg/apis/connector/v1alpha1/eureka.go
  pkg/apis/connector/v1alpha1/nacos.go
  pkg/apis/connector/v1alpha1/types.go
  pkg/configurator/methods.go
  pkg/configurator/mock_client_generated.go
  pkg/configurator/types.go
  pkg/connector/annotation.go
  pkg/connector/cli/config.go
  pkg/connector/controller.go
  pkg/connector/ctok/endpoint.go
  pkg/connector/ctok/source.go
  pkg/connector/ctok/syncer.go
  pkg/connector/ctok/types.go
  pkg/connector/discovery.go
  pkg/connector/ktoc/source.go
  pkg/connector/provider/consul.go
  pkg/gateway/cache/config.go
  pkg/gateway/cache/types.go
  pkg/gateway/cache/utils.go
  pkg/manager/listeners/client.go
  pkg/sidecar/providers/pipy/driver/pipy_container.go
Labels: enhancement

#222 fix: add resource limits to container of pipy repo
  charts/fsm/README.md
  charts/fsm/templates/fsm-deployment.yaml
  charts/fsm/values.schema.json
  charts/fsm/values.yaml
Labels: enhancement

#224 fix: add create namespace permission to fsm
  charts/fsm/templates/fsm-rbac.yaml
Labels: bug

#223 support disabling multi-level gateways.
  cmd/fsm-bootstrap/crds/connector.flomesh.io_consulconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_eurekaconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_machineconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_nacosconnectors.yaml
  pkg/apis/connector/v1alpha1/consul.go
  pkg/apis/connector/v1alpha1/eureka.go
  pkg/apis/connector/v1alpha1/machine.go
  pkg/apis/connector/v1alpha1/nacos.go
  pkg/apis/connector/v1alpha1/types.go
  pkg/apis/connector/v1alpha1/zz_generated.deepcopy.go
  pkg/connector/annotation.go
  pkg/connector/cli/config.go
  pkg/connector/controller.go
  pkg/connector/ctok/endpoint.go
  pkg/connector/ctok/source.go
  pkg/connector/ctok/types.go
  pkg/endpoint/types.go
  pkg/providers/kube/client.go
  pkg/sidecar/providers/pipy/repo/util.go
Labels: enhancement

#225 fix: add update/patch/delete namespace permission to fsm
  charts/fsm/templates/fsm-rbac.yaml
Labels: bug

#227 build(deps): Bump golang.org/x/net from 0.19.0 to 0.24.0
  go.mod
  go.sum
Labels: dependencies

#229 fix：invalid cloud service's name.
  pkg/connector/ctok/source.go
  pkg/connector/ctok/syncer.go
  pkg/connector/ctok/types.go
  pkg/connector/discovery.go
  pkg/connector/ktoc/source.go
  pkg/connector/ktoc/syncer.go
  pkg/connector/provider/nacos.go
  pkg/sidecar/providers/pipy/repo/policy.go
Labels: bug

#231 fix: ruleName for multi services.
  pkg/sidecar/providers/pipy/repo/policy.go
Labels: bug
