Repository flomesh-io/fsm, pull requests merged in 2024-05, with the labels that each got.

#234 feat: new annotations for FLB
  pkg/constants/constants.go
  pkg/controllers/flb/service_controller.go
  pkg/controllers/flb/types.go
Labels: enhancement

#235 refactor: extract code of generating pipy config to new struct
  pkg/gateway/cache/config.go
  pkg/gateway/cache/context.go
  pkg/gateway/cache/grpcroute.go
  pkg/gateway/cache/httproute.go
  pkg/gateway/cache/methods.go
  pkg/gateway/cache/policies.go
  pkg/gateway/cache/tcproute.go
  pkg/gateway/cache/tlsroute.go
  pkg/gateway/cache/udproute.go
Labels: enhancement

#236 feat: delete svc from FLB in case it's not a FLB service anymore
  pkg/controllers/flb/event_handlers.go
  pkg/controllers/flb/service_controller.go
Labels: enhancement

#237 docs: add supported version of GatewayAPI resources
  README.md
Labels: documentation

#238 fix: don't delete svc from cache if failed to delete svc from FLB
  pkg/controllers/flb/event_handlers.go
Labels: bug

#239 refactor: processing Gateway resources and generating config
  pkg/constants/constants.go
  pkg/controllers/gateway/v1/gateway_controller.go
  pkg/controllers/gateway/v1/httproute_controller.go
  pkg/controllers/gateway/v1alpha2/grpcroute_controller.go
  pkg/controllers/gateway/v1alpha2/tcproute_controller.go
  pkg/controllers/gateway/v1alpha2/tlsroute_controller.go
  pkg/controllers/gateway/v1alpha2/udproute_controller.go
  pkg/controllers/policyattachment/v1alpha1/accesscontrolpolicy_controller.go
  pkg/controllers/policyattachment/v1alpha1/faultinjectionpolicy_controller.go
  pkg/controllers/policyattachment/v1alpha1/gatewaytlspolicy_controller.go
  pkg/controllers/policyattachment/v1alpha1/ratelimitpolicy_controller.go
  pkg/gateway/cache/config.go
  pkg/gateway/cache/grpcroute.go
  pkg/gateway/cache/httproute.go
  pkg/gateway/cache/methods.go
  pkg/gateway/cache/policies.go
  pkg/gateway/cache/processor.go
  pkg/gateway/cache/tcproute.go
  pkg/gateway/cache/tlsroute.go
  pkg/gateway/cache/types.go
  pkg/gateway/cache/udproute.go
  pkg/gateway/status/route.go
  pkg/gateway/utils/utils.go
  pkg/k8s/informers/informers.go
  pkg/k8s/informers/types.go
Labels: enhancement

#240 build: bump pipy from 0.99.1-1 to 1.1.0-1
  charts/fsm/README.md
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  dockerfiles/Dockerfile.fsm-gateway
  dockerfiles/Dockerfile.fsm-ingress
  pkg/apis/config/v1alpha3/mesh_config.go
Labels: enhancement

#243 fix: add more variables to compute FLB svc hash
  pkg/controllers/flb/service_controller.go
Labels: bug

#244 fix: remove service hash annotation if it's not a FLB svc anymore
  pkg/controllers/flb/event_handlers.go
  pkg/controllers/flb/service_controller.go
Labels: bug

#246 fix: nacos password
  pkg/connector/provider/nacos.go
Labels: bug

#250 fix: compute FLB service hash
  pkg/controllers/flb/service_controller.go
Labels: bug

#249 test: mock server for testing FLB controller
  go.mod
  go.sum
  pkg/controllers/flb/service_controller.go
  pkg/controllers/flb/settings.go
  pkg/controllers/flb/tls_secret_controller.go
  pkg/controllers/flb/types.go
  pkg/flb/types.go
  tests/tools/mock-flb-api-server/main.go
Labels: enhancement

#252 feat: deprecate GatewayTLSPolicy
  charts/fsm/components/scripts.tar.gz
  charts/fsm/components/scripts/gateways/common/tls-termination.js
  charts/fsm/templates/fsm-rbac.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_gatewaytlspolicies.yaml
  docs/gateway-api-compatibility.md
  docs/tests/gateway-api/README.md
  pkg/announcements/types.go
  pkg/apis/policyattachment/v1alpha1/gatewaytls.go
  pkg/apis/policyattachment/v1alpha1/register.go
  pkg/apis/policyattachment/v1alpha1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controllers/policyattachment/v1alpha1/gatewaytlspolicy_controller.go
  pkg/gateway/cache/cache.go
  pkg/gateway/cache/configmaps_trigger.go
  pkg/gateway/cache/gatewaytls_trigger.go
  pkg/gateway/cache/methods.go
  pkg/gateway/cache/policies.go
  pkg/gateway/cache/processor.go
  pkg/gateway/cache/utils.go
  pkg/gateway/client.go
  pkg/gateway/fgw/types.go
  pkg/gateway/policy/port_enrichers.go
  pkg/gateway/policy/utils/gatewaytls/utils.go
  pkg/gen/client/policyattachment/clientset/versioned/typed/policyattachment/v1alpha1/fake/fake_gatewaytlspolicy.go
  pkg/gen/client/policyattachment/clientset/versioned/typed/policyattachment/v1alpha1/fake/fake_policyattachment_client.go
  pkg/gen/client/policyattachment/clientset/versioned/typed/policyattachment/v1alpha1/gatewaytlspolicy.go
  pkg/gen/client/policyattachment/clientset/versioned/typed/policyattachment/v1alpha1/generated_expansion.go
  pkg/gen/client/policyattachment/clientset/versioned/typed/policyattachment/v1alpha1/policyattachment_client.go
  pkg/gen/client/policyattachment/informers/externalversions/generic.go
  pkg/gen/client/policyattachment/informers/externalversions/policyattachment/v1alpha1/gatewaytlspolicy.go
  pkg/gen/client/policyattachment/informers/externalversions/policyattachment/v1alpha1/interface.go
  pkg/gen/client/policyattachment/listers/policyattachment/v1alpha1/expansion_generated.go
  pkg/gen/client/policyattachment/listers/policyattachment/v1alpha1/gatewaytlspolicy.go
  pkg/k8s/informers/informers.go
  pkg/k8s/informers/types.go
  pkg/manager/reconciler/reconcilers.go
  pkg/messaging/broker.go
  pkg/webhook/gatewaytls/webhook.go
  scripts/check-scripts.sh
  tests/e2e/e2e_gatewayapi_test.go
Labels: enhancement

#253 feat: use ParameterRef within Infrastructure to configure Gateway
  cmd/cli/install.go
  cmd/cli/mesh_upgrade.go
  docs/tests/gateway-api/README.md
  pkg/constants/constants.go
  pkg/controllers/gateway/v1/gateway_controller.go
  pkg/controllers/gateway/v1/utils.go
  pkg/helm/utils.go
  tests/e2e/e2e_gatewayapi_test.go
  tests/framework/common_apps.go
Labels: enhancement

#254 fix resources of init container injected with sidecar
  charts/fsm/values.schema.json
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/apis/config/v1alpha3/zz_generated.deepcopy.go
  pkg/configurator/methods.go
  pkg/configurator/mock_client_generated.go
  pkg/configurator/types.go
  pkg/injector/init_container.go
  pkg/injector/init_container_test.go
  pkg/manager/listeners/client.go
  pkg/sidecar/providers/pipy/driver/pipy_container.go
  pkg/sidecar/providers/pipy/driver/sidecar.go
Labels: enhancement

#255 feat: ensure values from MeshConfig override the values from gateway ParameteRef
  pkg/controllers/gateway/v1/gateway_controller.go
Labels: enhancement

#256 fix: clean up LoadBalancer address if it's not FLB svc anymore
  pkg/controllers/flb/event_handlers.go
Labels: bug

#257 feat: support HPA and PDB for gateway
  charts/gateway/README.md
  charts/gateway/templates/hpa.yaml
  charts/gateway/templates/pod-disruption-budget.yaml
  charts/gateway/values.yaml
Labels: enhancement

#258 feat: use Endpoints to calculate backend addresses if k8s version is under 1.21
  .github/workflows/main.yml
  charts/fsm/README.md
  charts/fsm/templates/fsm-rbac.yaml
  charts/fsm/templates/preset-mesh-config.yaml
  charts/fsm/values.schema.json
  charts/fsm/values.yaml
  charts/gateway/templates/deployment.yaml
  charts/gateway/templates/pod-disruption-budget.yaml
  charts/gateway/templates/role.yaml
  charts/gateway/templates/rolebinding.yaml
  charts/gateway/templates/route.yaml
  charts/gateway/templates/service-tcp.yaml
  charts/gateway/templates/service-udp.yaml
  charts/gateway/templates/serviceaccount.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/connector/ctok/endpoint.go
  pkg/controllers/gateway/v1/gateway_controller.go
  pkg/controllers/servicelb/service_controller.go
  pkg/gateway/cache/cache.go
  pkg/gateway/cache/endpoints_trigger.go
  pkg/gateway/cache/endpointslices_trigger.go
  pkg/gateway/cache/methods.go
  pkg/gateway/cache/processor.go
  pkg/gateway/cache/types.go
  pkg/gateway/cache/utils.go
  pkg/utils/ip.go
  pkg/version/utils.go
  tests/e2e/e2e_gatewayapi_test.go
Labels: enhancement

#260 remove useless k8s informer
  cmd/fsm-connector/fsm-connector.go
  pkg/connector/ctok/endpoint.go
  pkg/connector/ctok/syncer.go
  pkg/messaging/broker.go
Labels: enhancement

#261 feat: generate register code instead of maintaining manually
  codegen/gen-crd-client.sh
  pkg/apis/config/v1alpha1/register.go
  pkg/apis/config/v1alpha1/zz_generated.register.go
  pkg/apis/config/v1alpha2/register.go
  pkg/apis/config/v1alpha2/zz_generated.register.go
  pkg/apis/config/v1alpha3/register.go
  pkg/apis/config/v1alpha3/zz_generated.register.go
  pkg/apis/connector/v1alpha1/register.go
  pkg/apis/connector/v1alpha1/zz_generated.register.go
  pkg/apis/machine/v1alpha1/register.go
  pkg/apis/machine/v1alpha1/zz_generated.register.go
  pkg/apis/multicluster/v1alpha1/register.go
  pkg/apis/multicluster/v1alpha1/zz_generated.register.go
  pkg/apis/namespacedingress/v1alpha1/register.go
  pkg/apis/namespacedingress/v1alpha1/zz_generated.register.go
  pkg/apis/networking/v1/register.go
  pkg/apis/networking/v1/zz_generated.register.go
  pkg/apis/plugin/v1alpha1/register.go
  pkg/apis/plugin/v1alpha1/zz_generated.register.go
  pkg/apis/policy/v1alpha1/register.go
  pkg/apis/policy/v1alpha1/zz_generated.register.go
  pkg/apis/policyattachment/v1alpha1/register.go
  pkg/apis/policyattachment/v1alpha1/zz_generated.register.go
Labels: enhancement

#263 fix: use image flomesh/fsm-curl instead of curlimages/curl
  charts/fsm/templates/preset-mesh-config.yaml
  charts/gateway/README.md
  charts/gateway/templates/_helpers.tpl
  charts/gateway/templates/deployment.yaml
  charts/gateway/values.yaml
  charts/namespaced-ingress/README.md
  charts/namespaced-ingress/templates/_helpers.tpl
  charts/namespaced-ingress/templates/deployment.yaml
  charts/namespaced-ingress/values.yaml
  cmd/cli/ingress_enable.go
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/configurator/methods.go
  pkg/configurator/mock_client_generated.go
  pkg/configurator/types.go
  pkg/controllers/gateway/v1/gateway_controller.go
  pkg/controllers/namespacedingress/v1alpha1/namespacedingress_controller.go
  pkg/manager/listeners/client.go
  tests/e2e/e2e_client_server_connectivity_test.go
  tests/e2e/e2e_retry_policy_test.go
  tests/e2e/e2e_smi_traffic_target_test.go
  tests/e2e/e2e_upgrade_test.go
Labels: enhancement

#264 fix: determine if gateway infrastructure is nil
  charts/gateway/templates/deployment.yaml
  charts/gateway/templates/service-tcp.yaml
  charts/gateway/templates/service-udp.yaml
Labels: bug

#265 build(deps): bump k8s api to 0.30.1
  cmd/fsm-bootstrap/crds/networking.flomesh.io_namespacedingresses.yaml
  codegen/gen-crd-client.sh
  go.mod
  go.sum
Labels: enhancement

#270 [backport] fix: delete multi cluster service and propagate it to all joined clusters
  pkg/mcs/remote/types.go
Labels: bug

#267 fix: delete multi cluster service and propagate it to all joined clus…
  pkg/mcs/remote/types.go
  scripts/k3d-multicluster-deploy-apps.sh
Labels: bug

#271 feat: validate Gateway resources by code in case CustomResourceValidationExpressions is not supported
  pkg/apis/gateway/v1/util/validation/gatewayclass.go
  pkg/apis/gateway/v1/util/validation/gatewayclass_test.go
  pkg/apis/gateway/v1/validation/common.go
  pkg/apis/gateway/v1/validation/common_test.go
  pkg/apis/gateway/v1/validation/doc.go
  pkg/apis/gateway/v1/validation/gateway.go
  pkg/apis/gateway/v1/validation/gateway_test.go
  pkg/apis/gateway/v1/validation/gatewayclass.go
  pkg/apis/gateway/v1/validation/gatewayclass_test.go
  pkg/apis/gateway/v1/validation/grpcroute.go
  pkg/apis/gateway/v1/validation/grpcroute_test.go
  pkg/apis/gateway/v1/validation/httproute.go
  pkg/apis/gateway/v1/validation/httproute_test.go
  pkg/apis/gateway/v1alpha2/util/validation/gatewayclass.go
  pkg/apis/gateway/v1alpha2/validation/common.go
  pkg/apis/gateway/v1alpha2/validation/doc.go
  pkg/apis/gateway/v1alpha2/validation/tcproute.go
  pkg/apis/gateway/v1alpha2/validation/tcproute_test.go
  pkg/apis/gateway/v1alpha2/validation/tlsroute.go
  pkg/apis/gateway/v1alpha2/validation/tlsroute_test.go
  pkg/apis/gateway/v1alpha2/validation/udproute.go
  pkg/apis/gateway/v1alpha2/validation/udproute_test.go
  pkg/apis/gateway/v1alpha2/validation/utils_test.go
  pkg/apis/gateway/v1beta1/util/validation/gatewayclass.go
  pkg/apis/gateway/v1beta1/util/validation/gatewayclass_test.go
  pkg/apis/gateway/v1beta1/validation/common.go
  pkg/apis/gateway/v1beta1/validation/common_test.go
  pkg/apis/gateway/v1beta1/validation/doc.go
  pkg/version/utils.go
  pkg/webhook/gateway/gateway_webhook.go
  pkg/webhook/grpcroute/grpcroute_webhook.go
  pkg/webhook/httproute/httproute_webhook.go
  pkg/webhook/tcproute/tcproute_webhook.go
  pkg/webhook/tlsroute/tlsproute_webhook.go
  pkg/webhook/udproute/udproute_webhook.go
Labels: bug

#277 fix: ControllerName of gateway class is not editable
  pkg/apis/gateway/v1/validation/gatewayclass.go
  pkg/webhook/gatewayclass/gatewayclass_webhook.go
Labels: bug

#278 build(deps): bump klipper-lb to 0.4.7
  charts/fsm/README.md
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
Labels: enhancement
