Repository flomesh-io/fsm, pull requests merged in 2024-07, with the labels that each got.

#300 build(deps): bump pipy from 1.2.0 to 1.3.0
  charts/fsm/README.md
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  dockerfiles/Dockerfile.fsm-gateway
  dockerfiles/Dockerfile.fsm-ingress
  docs/tests/gateway-api/README.md
  pkg/apis/config/v1alpha3/mesh_config.go
  scripts/k3d-multicluster-deploy-apps.sh
  tests/e2e/e2e_fsm_ingress_test.go
  tests/e2e/e2e_gatewayapi_test.go
Labels: dependencies

#303 fix: Grafana dashboard issue due to legacy sidecarClass configuration
  charts/fsm/grafana/pipy/dashboards/fsm-control-plane.json
  charts/fsm/grafana/pipy/dashboards/fsm-data-plane-performance.json
  charts/fsm/grafana/pipy/dashboards/fsm-mesh-sidecar-details.json
  charts/fsm/templates/fsm-deployment.yaml
  charts/fsm/templates/grafana-configmap.yaml
  charts/fsm/templates/prometheus-configmap.yaml
Labels: bug

#304 fix: check policy status when generating config
  pkg/gateway/processor/v2/backend_lb_policy.go
  pkg/gateway/processor/v2/backend_tls_policy.go
  pkg/gateway/processor/v2/health_check_policy.go
  pkg/gateway/processor/v2/retry_policy.go
  pkg/gateway/utils/policies.go
Labels: enhancement

#305 fix: missing updating status of GatewayAPI resources
  pkg/controllers/gateway/v1/gateway_controller.go
  pkg/gateway/processor/v2/backend_tls_policy.go
  pkg/gateway/status/routes/processor.go
  pkg/gateway/status/status.go
Labels: bug

#306 fix: traffic split didn't work as expected with keep-alive connections
  pkg/sidecar/providers/pipy/repo/codebase/modules/outbound-http-routing.js
Labels: bug

#308 build(deps): bump k8s deps version from 0.30.1 to 0.30.2
  codegen/gen-crd-client.sh
  go.mod
  go.sum
Labels: enhancement, dependencies

#314 fix: generate 16 bytes trace id
  charts/fsm/components/scripts.tar.gz
  charts/fsm/components/scripts/gateways/lib/logging.js
  charts/fsm/components/scripts/gateways/lib/tracing.js
  pkg/sidecar/providers/pipy/repo/codebase/logging.js
  pkg/sidecar/providers/pipy/repo/codebase/tracing.js
Labels: bug

#315 build(deps): bump to latest fgw scripts
  charts/fsm/components/scripts.tar.gz
  charts/fsm/components/scripts/gateways/modules/backend-selector.js
  charts/fsm/components/scripts/gateways/modules/forward-http.js
  charts/fsm/components/scripts/gateways/modules/route-http.js
  charts/fsm/components/scripts/gateways/modules/route-tcp.js
  charts/fsm/components/scripts/gateways/modules/route-tls.js
  charts/fsm/components/scripts/gateways/modules/route-udp.js
Labels: enhancement

#316 fix: sidecar log issues
  charts/fsm/README.md
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/sidecar/providers/pipy/repo/policy.go
Labels: enhancement
