Repository flomesh-io/fsm, pull requests merged in 2024-10, with the labels that each got.

#368 feat: build image on runner of target platform
  .github/workflows/build-pipy-euler.yml
  .github/workflows/build-pipy-nonroot.yml
Labels: enhancement

#371 feat: GEP-3171 Percentage-based request mirroring
  pkg/gateway/fgw/config.go
  pkg/gateway/processor/v2/grpcroute.go
  pkg/gateway/processor/v2/httproute.go
Labels: enhancement

#373 feat: add headers to access log
  charts/fsm/components/scripts.tar.gz
  charts/fsm/components/scripts/gateways/filters/http/AccessLog.js
  main.go
Labels: enhancement

#372 feat: generate BackendTLSPolicy config according to gateway-api 1.2.0 changes
  pkg/gateway/fgw/config.go
Labels: enhancement

#374 fix: nullable fields of CRD
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_filters.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_listenerfilters.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_healthcheckpolicies.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_retrypolicies.yaml
  pkg/apis/extension/v1alpha1/circuitbreaker.go
  pkg/apis/extension/v1alpha1/faultinjection.go
  pkg/apis/extension/v1alpha1/filter.go
  pkg/apis/extension/v1alpha1/filterconfig.go
  pkg/apis/extension/v1alpha1/filterdefinition.go
  pkg/apis/extension/v1alpha1/httplog.go
  pkg/apis/extension/v1alpha1/listenerfilter.go
  pkg/apis/extension/v1alpha1/ratelimit.go
  pkg/apis/policyattachment/v1alpha2/healthcheck.go
  pkg/apis/policyattachment/v1alpha2/retry.go
Labels: bug

#375 fixed isolation policy with fgw.
  pkg/gateway/processor/v2/utils.go
  tests/e2e/e2e_statefulsets_test.go
Labels: bug

#376 refactor: cleanup unused values
  charts/fsm/README.md
  charts/fsm/templates/preset-mesh-config.yaml
  charts/fsm/values.schema.json
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
Labels: enhancement

#377 feat: new Access Log format
  charts/fsm/components/scripts.tar.gz
  charts/fsm/components/scripts/gateways/filters/http/AccessLog.js
Labels: enhancement

#378 refactor: remove legacy FGW configurations
  charts/fsm/README.md
  charts/fsm/templates/preset-mesh-config.yaml
  charts/fsm/values.schema.json
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/apis/config/v1alpha3/zz_generated.deepcopy.go
  pkg/configurator/methods.go
  pkg/configurator/mock_client_generated.go
  pkg/configurator/types.go
  pkg/manager/listeners/client.go
Labels: enhancement

#379 feat: GEP-1731 HTTPRoute Retry support
  pkg/gateway/fgw/config.go
Labels: enhancement

#382 add mustWithNamespace option into meshconfig.
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/catalog/inbound_traffic_policies_test.go
  pkg/catalog/outbound_traffic_policies_test.go
  pkg/k8s/util.go
  pkg/k8s/util_test.go
Labels: enhancement

#385 build(deps): Bump golang.org/x/image from 0.14.0 to 0.18.0
  go.mod
  go.sum
Labels: enhancement, dependencies

#386 fix connector source check.
  pkg/connector/ktog/gateway.go
Labels: bug

#391 add fixed service port option.
  cmd/fsm-bootstrap/crds/connector.flomesh.io_consulconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_eurekaconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_nacosconnectors.yaml
  pkg/apis/connector/v1alpha1/consul.go
  pkg/apis/connector/v1alpha1/eureka.go
  pkg/apis/connector/v1alpha1/nacos.go
  pkg/apis/connector/v1alpha1/zz_generated.deepcopy.go
  pkg/connector/cli/config.go
  pkg/connector/controller.go
  pkg/connector/ctok/syncer.go
  pkg/sidecar/providers/pipy/repo/util.go
Labels: enhancement

#393 fix issues(isolation policy, pjs and stale files).
  pkg/catalog/catalog.go
  pkg/catalog/isolation.go
  pkg/catalog/mock_catalog_generated.go
  pkg/catalog/types.go
  pkg/gateway/processor/v2/config.go
  pkg/gateway/processor/v2/utils.go
  pkg/messaging/broker.go
  pkg/repo/client.go
  pkg/repo/types.go
  pkg/sidecar/providers/pipy/proxy.go
  pkg/sidecar/providers/pipy/repo/codebase/modules/inbound-http-routing.js
  pkg/sidecar/providers/pipy/repo/codebase/modules/outbound-http-routing.js
  pkg/sidecar/providers/pipy/repo/jobs.go
Labels: bug

#392 fix: delete stale files from gateway codebase
  pkg/gateway/processor/v2/config.go
  pkg/repo/client.go
  pkg/repo/types.go
Labels: bug

#394 feature: delete codebase when gateway is deleted
  pkg/controllers/gateway/v1/gateway_controller.go
  pkg/repo/client.go
Labels: enhancement

#397 fix: output weight field of 0-weight backend
  pkg/gateway/fgw/config.go
  pkg/gateway/processor/v2/grpcroute.go
  pkg/gateway/processor/v2/httproute.go
  pkg/gateway/processor/v2/tcproute.go
  pkg/gateway/processor/v2/tlsroute.go
  pkg/gateway/processor/v2/udproute.go
  pkg/gateway/processor/v2/utils.go
Labels: enhancement

#398 fixed traffic split for connector.
  pkg/gateway/processor/v2/backends.go
  pkg/k8s/client.go
  pkg/smi/client.go
Labels: enhancement

#389 feat: [GEP-3155] Complete Backend mutual TLS Configuration
  go.mod
  go.sum
  pkg/controllers/gateway/v1/gateway_controller.go
  pkg/controllers/gateway/v1/types.go
  pkg/controllers/gateway/v1beta1/referencegrant_controller.go
  pkg/gateway/fgw/config.go
  pkg/gateway/processor/v2/backend_tls_policy.go
  pkg/gateway/processor/v2/gateway.go
  pkg/gateway/processor/v2/generator.go
  pkg/gateway/processor/v2/types.go
  pkg/gateway/status/gw/gateway.go
  pkg/gateway/status/routes/processor.go
  pkg/gateway/status/routes/types.go
  pkg/gateway/types/types.go
  pkg/gateway/utils/certificates.go
  pkg/gateway/utils/referencegrants.go
  tests/e2e/e2e_gatewayapi_test.go
Labels: enhancement

#400 [backport] build(deps): bump pipy to 1.5.2 (#399)
  charts/fsm/README.md
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  dockerfiles/Dockerfile.fsm-gateway
  dockerfiles/Dockerfile.fsm-ingress
  docs/tests/gateway-api/README.md
  pkg/apis/config/v1alpha3/mesh_config.go
  tests/e2e/e2e_fsm_ingress_test.go
  tests/e2e/e2e_gatewayapi_test.go
Labels: enhancement

#401 feat: backend protocol selection
  pkg/constants/constants.go
  pkg/controllers/gateway/v1/grpcroute_controller.go
  pkg/controllers/gateway/v1/httproute_controller.go
  pkg/controllers/gateway/v1alpha2/tcproute_controller.go
  pkg/controllers/gateway/v1alpha2/tlsroute_controller.go
  pkg/controllers/gateway/v1alpha2/udproute_controller.go
  pkg/gateway/fgw/config.go
  pkg/gateway/processor/v2/backends.go
  pkg/gateway/processor/v2/grpcroute.go
  pkg/gateway/processor/v2/httproute.go
  pkg/gateway/processor/v2/tcproute.go
  pkg/gateway/processor/v2/tlsroute.go
  pkg/gateway/processor/v2/types.go
  pkg/gateway/processor/v2/udproute.go
  pkg/gateway/status/routes/backendlb.go
  pkg/gateway/status/routes/backendtls.go
  pkg/gateway/status/routes/grpcroute.go
  pkg/gateway/status/routes/healthcheck.go
  pkg/gateway/status/routes/httproute.go
  pkg/gateway/status/routes/processor.go
  pkg/gateway/status/routes/retry.go
  pkg/gateway/status/routes/tcproute.go
  pkg/gateway/status/routes/udproute.go
  pkg/gateway/utils/backends.go
Labels: enhancement

#402 feat: transform appProtocol to FGW format when generating configuration
  pkg/gateway/processor/v2/backends.go
  pkg/gateway/processor/v2/tlsroute.go
  pkg/gateway/processor/v2/utils.go
Labels: enhancement

#403 build(deps): bump helm from 3.14.3 to 3.16.2
  Makefile
  go.mod
  go.sum
Labels: enhancement

#405 [security]fix: Vault Community Edition privilege escalation vulnerabi…
  go.mod
  go.sum
Labels: enhancement

#404 feat: integrate gwctl code and bump deps
  Makefile
  cmd/cli/analyze/analyze.go
  cmd/cli/apply/apply.go
  cmd/cli/delete/delete.go
  cmd/cli/fsm.go
  cmd/cli/get/get.go
  cmd/cli/proxy.go
  cmd/cli/proxy_get.go
  go.mod
  go.sum
  pkg/cli/common/clients.go
  pkg/cli/common/errors.go
  pkg/cli/common/factory.go
  pkg/cli/common/testhelpers.go
  pkg/cli/common/types.go
  pkg/cli/environment.go
  pkg/cli/extension/directlyattachedpolicy/directlyattachedpolicy.go
  pkg/cli/extension/extensions.go
  pkg/cli/extension/gatewayeffectivepolicy/gatewayeffectivepolicy.go
  pkg/cli/extension/notfoundrefvalidator/notfoundrefvalidator.go
  pkg/cli/extension/refgrantvalidator/refgrantvalidator.go
  pkg/cli/extension/utils/utils.go
  pkg/cli/flags/flags.go
  pkg/cli/policymanager/helpers.go
  pkg/cli/policymanager/manager.go
  pkg/cli/policymanager/merger.go
  pkg/cli/policymanager/merger_test.go
  pkg/cli/policymanager/types.go
  pkg/cli/printer/backends.go
  pkg/cli/printer/backends_test.go
  pkg/cli/printer/gatewayclasses.go
  pkg/cli/printer/gatewayclasses_test.go
  pkg/cli/printer/gateways.go
  pkg/cli/printer/gateways_test.go
  pkg/cli/printer/httproutes.go
  pkg/cli/printer/httproutes_test.go
  pkg/cli/printer/main_test.go
  pkg/cli/printer/namespace.go
  pkg/cli/printer/namespace_test.go
  pkg/cli/printer/policies.go
  pkg/cli/printer/policies_test.go
  pkg/cli/printer/printer.go
  pkg/cli/printer/types.go
  pkg/cli/printer/utils.go
  pkg/cli/printer/utils_test.go
  pkg/cli/topology/gateway/gateway.go
  pkg/cli/topology/gateway/graphviz.go
  pkg/cli/topology/graph.go
  pkg/cli/topology/graph_test.go
  pkg/cli/topology/utils.go
Labels: enhancement

#406 feature: bump FGW to 1.5.0 to support GatewayAPI 1.2.0 features
  charts/fsm/components/scripts.tar.gz
  charts/fsm/components/scripts/gateways/filters/http/RequestMirror.js
  charts/fsm/components/scripts/gateways/modules/backend-tls.js
  charts/fsm/components/scripts/gateways/modules/backend.js
  charts/fsm/components/scripts/gateways/modules/balancer-http.js
  charts/fsm/components/scripts/gateways/modules/balancer-tcp.js
  charts/fsm/components/scripts/gateways/modules/router-http.js
  charts/fsm/components/scripts/gateways/modules/router-tcp.js
  charts/fsm/components/scripts/gateways/modules/router-tls.js
  charts/fsm/components/scripts/gateways/startup.js
Labels: enhancement

#407 build(deps): bump pipy to 1.5.3
  charts/fsm/README.md
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  dockerfiles/Dockerfile.fsm-gateway
  dockerfiles/Dockerfile.fsm-ingress
  docs/tests/gateway-api/README.md
  pkg/apis/config/v1alpha3/mesh_config.go
  tests/e2e/e2e_fsm_ingress_test.go
  tests/e2e/e2e_gatewayapi_test.go
Labels: enhancement
