Repository flomesh-io/fsm, pull requests merged in 2024-01, with the labels that each got.

#165 update api reference doc generation config
  docs/api_reference/config.json
Labels: enhancement

#169 feat: gateway supports coexistence of TCP and UDP listener
  charts/gateway/templates/service-tcp.yaml
  charts/gateway/templates/service-udp.yaml
  docs/tests/gateway-api/README.md
  pkg/controllers/gateway/v1beta1/gateway_controller.go
Labels: enhancement

#170 docs: fix a typo
  pkg/apis/policyattachment/v1alpha1/doc.go
Labels: bug, documentation

#168 [chore] Update FLB docs for defaultAlgo.
  charts/fsm/README.md
  charts/fsm/values.yaml
Labels: documentation

#173 fix: incorrect update annotation of FLB svc
  pkg/controllers/flb/service_controller.go
Labels: bug

#174 fix: assignment entry to nil map
  cmd/fsm-bootstrap/fsm-bootstrap.go
Labels: bug

#175 fix: cloud connector issuses
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/catalog/access_control.go
  pkg/connector/cli/sync.go
  pkg/connector/ctok/sink.go
  pkg/connector/ctok/source.go
  pkg/connector/ctok/types.go
  pkg/connector/provider/consul.go
  pkg/connector/provider/types.go
  pkg/connector/types.go
  pkg/connector/watcher.go
  pkg/providers/kube/client.go
  pkg/providers/kube/client_test.go
  pkg/sidecar/providers/pipy/repo/util.go
Labels: bug

#176 fix: fgw http route's hostnames.
  pkg/connector/ktog/gateway.go
Labels: enhancement

#179 feat: support setting replicas and resource limits of Gateway
  charts/gateway/README.md
  charts/gateway/templates/deployment.yaml
  charts/gateway/templates/hpa.yaml
  charts/gateway/templates/pod-disruption-budget.yaml
  charts/gateway/values.yaml
  docs/tests/gateway-api/README.md
  pkg/constants/constants.go
  pkg/controllers/gateway/v1beta1/gateway_controller.go
  pkg/controllers/gateway/v1beta1/utils.go
Labels: enhancement

#180 feat: propagate labels and annotations to each resource generated for a gateway
  charts/gateway/templates/deployment.yaml
  charts/gateway/templates/service-tcp.yaml
  charts/gateway/templates/service-udp.yaml
  docs/tests/gateway-api/README.md
Labels: enhancement

#181 feat: add label gateway.networking.k8s.io/policy=true to FSM policy attachment
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_accesscontrolpolicies.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_circuitbreakingpolicies.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_faultinjectionpolicies.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_gatewaytlspolicies.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_healthcheckpolicies.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_loadbalancerpolicies.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_ratelimitpolicies.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_retrypolicies.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_sessionstickypolicies.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_upstreamtlspolicies.yaml
  pkg/apis/policyattachment/v1alpha1/accesscontrol.go
  pkg/apis/policyattachment/v1alpha1/circuitbreaking.go
  pkg/apis/policyattachment/v1alpha1/faultinjection.go
  pkg/apis/policyattachment/v1alpha1/gatewaytls.go
  pkg/apis/policyattachment/v1alpha1/healthcheck.go
  pkg/apis/policyattachment/v1alpha1/loadbalancer.go
  pkg/apis/policyattachment/v1alpha1/ratelimit.go
  pkg/apis/policyattachment/v1alpha1/retry.go
  pkg/apis/policyattachment/v1alpha1/sessionsticky.go
  pkg/apis/policyattachment/v1alpha1/upstreamtls.go
Labels: enhancement

#182 fix: reduce the possibility of wrongly configuring remote logging
  charts/fsm/templates/preset-mesh-config.yaml
Labels: enhancement

#183 fix: status of Gateway IP addresses due to service name changed
  pkg/constants/constants.go
  pkg/controllers/gateway/v1beta1/gateway_controller.go
Labels: bug
