Repository flomesh-io/fsm, pull requests merged in 2024-11, with the labels that each got.

#411 refactor: remove RetryPolicy
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_retrypolicies.yaml
  codegen/gen-crd-client.sh
  pkg/announcements/types.go
  pkg/apis/policyattachment/v1alpha2/retry.go
  pkg/apis/policyattachment/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/policyattachment/v1alpha2/zz_generated.register.go
  pkg/controllers/gateway/v1/httproute_controller.go
  pkg/controllers/policyattachment/v1alpha2/retrypolicy_controller.go
  pkg/gateway/client.go
  pkg/gateway/fgw/config.go
  pkg/gateway/informers.go
  pkg/gateway/processor/triggers/policy/v2/retries_trigger.go
  pkg/gateway/processor/v2/generator.go
  pkg/gateway/processor/v2/policies.go
  pkg/gateway/processor/v2/processor.go
  pkg/gateway/processor/v2/retry_policy.go
  pkg/gateway/status/policies/policy.go
  pkg/gateway/status/routes/httproute.go
  pkg/gateway/status/routes/retry.go
  pkg/gateway/status/status.go
  pkg/gateway/utils/backends.go
  pkg/gen/client/policyattachment/clientset/versioned/typed/policyattachment/v1alpha2/fake/fake_policyattachment_client.go
  pkg/gen/client/policyattachment/clientset/versioned/typed/policyattachment/v1alpha2/fake/fake_retrypolicy.go
  pkg/gen/client/policyattachment/clientset/versioned/typed/policyattachment/v1alpha2/generated_expansion.go
  pkg/gen/client/policyattachment/clientset/versioned/typed/policyattachment/v1alpha2/policyattachment_client.go
  pkg/gen/client/policyattachment/clientset/versioned/typed/policyattachment/v1alpha2/retrypolicy.go
  pkg/gen/client/policyattachment/informers/externalversions/generic.go
  pkg/gen/client/policyattachment/informers/externalversions/policyattachment/v1alpha2/interface.go
  pkg/gen/client/policyattachment/informers/externalversions/policyattachment/v1alpha2/retrypolicy.go
  pkg/gen/client/policyattachment/listers/policyattachment/v1alpha2/expansion_generated.go
  pkg/gen/client/policyattachment/listers/policyattachment/v1alpha2/retrypolicy.go
  pkg/k8s/informers/informers.go
  pkg/k8s/informers/types.go
  pkg/manager/reconciler/registers.go
  pkg/manager/reconciler/types.go
  pkg/messaging/broker.go
  pkg/webhook/policyattachment/v1alpha2/retry.go
Labels: enhancement

#413 build(deps): Bump github.com/hashicorp/vault from 1.18.0 to 1.18.1
  go.mod
  go.sum
Labels: enhancement

#415 remove init container from connector deployment.
  charts/connector/README.md
  charts/connector/templates/_helpers.tpl
  charts/connector/templates/deployment.yaml
  charts/connector/values.schema.json
  charts/connector/values.yaml
Labels: enhancement

#416 [cherry-pick] remove init container from connector deployment. (#415)
  charts/connector/README.md
  charts/connector/templates/_helpers.tpl
  charts/connector/templates/deployment.yaml
  charts/connector/values.schema.json
  charts/connector/values.yaml
Labels: enhancement

#418 build(deps): bump GatewayAPI from 1.1.0 to 1.1.1
  cmd/fsm-bootstrap/crds/backendtlspolicies.gateway.networking.k8s.io.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_backendlbpolicies.yaml
  cmd/fsm-bootstrap/crds/gatewayclasses.gateway.networking.k8s.io.yaml
  cmd/fsm-bootstrap/crds/gateways.gateway.networking.k8s.io.yaml
  cmd/fsm-bootstrap/crds/grpcroutes.gateway.networking.k8s.io.yaml
  cmd/fsm-bootstrap/crds/httproutes.gateway.networking.k8s.io.yaml
  cmd/fsm-bootstrap/crds/referencegrants.gateway.networking.k8s.io.yaml
  cmd/fsm-bootstrap/crds/tcproutes.gateway.networking.k8s.io.yaml
  cmd/fsm-bootstrap/crds/tlsroutes.gateway.networking.k8s.io.yaml
  cmd/fsm-bootstrap/crds/udproutes.gateway.networking.k8s.io.yaml
  cmd/fsm-bootstrap/raw/gateway-api.yaml
  go.mod
  go.sum
Labels: enhancement

#419 feat: conditionally drop route rule if no available backends
  charts/fsm/README.md
  charts/fsm/templates/preset-mesh-config.yaml
  charts/fsm/values.schema.json
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/gateway/processor/v2/backends.go
  pkg/gateway/processor/v2/config.go
  pkg/gateway/processor/v2/generator.go
  pkg/gateway/processor/v2/grpcroute.go
  pkg/gateway/processor/v2/httproute.go
  pkg/gateway/processor/v2/tcproute.go
  pkg/gateway/processor/v2/types.go
  pkg/gateway/processor/v2/udproute.go
Labels: enhancement

#421 [cherry-pick] feat: conditionally drop route rule if no available backends
  charts/fsm/README.md
  charts/fsm/templates/preset-mesh-config.yaml
  charts/fsm/values.schema.json
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  codegen/gen-crd-client.sh
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/gateway/processor/v2/backends.go
  pkg/gateway/processor/v2/config.go
  pkg/gateway/processor/v2/generator.go
  pkg/gateway/processor/v2/grpcroute.go
  pkg/gateway/processor/v2/httproute.go
  pkg/gateway/processor/v2/tcproute.go
  pkg/gateway/processor/v2/types.go
  pkg/gateway/processor/v2/udproute.go
Labels: enhancement

#422 ci(deps): bump trivy from 0.23.0 to 0.57.0
  Makefile
Labels: enhancement, github_actions

#423 [backport] ci(deps): bump trivy from 0.23.0 to 0.57.0 (#422)
  Makefile
Labels: enhancement

#424 fix: connector issues
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/apis/config/v1alpha3/zz_generated.deepcopy.go
  pkg/catalog/outbound_traffic_policies.go
  pkg/connector/ctok/source.go
  pkg/connector/ctok/syncer.go
  pkg/k8s/client.go
  pkg/providers/kube/client.go
  pkg/sidecar/providers/pipy/repo/jobs.go
  pkg/sidecar/providers/pipy/repo/policy.go
Labels: enhancement

#425 [cherry-pick] fix: connector issues (#424)
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/apis/config/v1alpha3/zz_generated.deepcopy.go
  pkg/catalog/outbound_traffic_policies.go
  pkg/connector/ctok/source.go
  pkg/connector/ctok/syncer.go
  pkg/k8s/client.go
  pkg/providers/kube/client.go
  pkg/sidecar/providers/pipy/repo/jobs.go
  pkg/sidecar/providers/pipy/repo/policy.go
Labels: enhancement

#426 fix: copy HTTPRouteFilters
  pkg/gateway/processor/v2/generator.go
  pkg/gateway/processor/v2/grpcroute.go
  pkg/gateway/processor/v2/httproute.go
  pkg/gateway/processor/v2/tcproute.go
  pkg/gateway/processor/v2/types.go
  pkg/gateway/processor/v2/udproute.go
Labels: bug

#428 [cherry-pick] fix: copy HTTPRouteFilters (#426)
  pkg/gateway/processor/v2/generator.go
  pkg/gateway/processor/v2/grpcroute.go
  pkg/gateway/processor/v2/httproute.go
  pkg/gateway/processor/v2/tcproute.go
  pkg/gateway/processor/v2/types.go
  pkg/gateway/processor/v2/udproute.go
Labels: bug

#429 refactor: simplify methods
  pkg/controllers/gateway/v1/grpcroute_controller.go
  pkg/controllers/gateway/v1/httproute_controller.go
  pkg/controllers/gateway/v1alpha2/tcproute_controller.go
  pkg/controllers/gateway/v1alpha2/tlsroute_controller.go
  pkg/controllers/gateway/v1alpha2/udproute_controller.go
  pkg/gateway/processor/v2/grpcroute.go
  pkg/gateway/processor/v2/health_check_policy.go
  pkg/gateway/processor/v2/httproute.go
  pkg/gateway/processor/v2/tcproute.go
  pkg/gateway/processor/v2/tlsroute.go
  pkg/gateway/processor/v2/udproute.go
  pkg/gateway/status/policies/policy.go
  pkg/gateway/status/routes/backendlb.go
  pkg/gateway/status/routes/backendtls.go
  pkg/gateway/status/routes/healthcheck.go
  pkg/gateway/status/routes/processor.go
  pkg/gateway/status/routes/route.go
  pkg/gateway/status/types.go
  pkg/gateway/utils/gateway.go
Labels: enhancement

#432 build(deps): bump fgw from 1.5.0 to 1.5.1
  charts/fsm/components/scripts.tar.gz
  charts/fsm/components/scripts/gateways/main.js
  charts/fsm/components/scripts/gateways/modules/balancer-http.js
  charts/fsm/components/scripts/gateways/startup.js
  charts/fsm/components/scripts/gateways/utils.js
Labels: enhancement

#433 CI: refactor workflow of building pipy images
  .github/workflows/build-pipy-euler.yml
  .github/workflows/build-pipy-images.yml
  dockerfiles/Dockerfile.euler
  dockerfiles/Dockerfile.fsm-gateway
  dockerfiles/Dockerfile.fsm-ingress
Labels: enhancement

#434 fix: merge values when gateway parameters is empty
  pkg/controllers/gateway/v1/gateway_controller.go
Labels: bug

#435 fix: trigger xRoutes to reconcile when gateway/backend status changed
  pkg/controllers/gateway/v1/grpcroute_controller.go
  pkg/controllers/gateway/v1/httproute_controller.go
  pkg/controllers/gateway/v1alpha2/tcproute_controller.go
  pkg/controllers/gateway/v1alpha2/tlsroute_controller.go
  pkg/controllers/gateway/v1alpha2/udproute_controller.go
Labels: bug

#436 [backport] fix: trigger xRoutes to reconcile when gateway/backend status changed
  pkg/controllers/gateway/v1/grpcroute_controller.go
  pkg/controllers/gateway/v1/httproute_controller.go
  pkg/controllers/gateway/v1alpha2/tcproute_controller.go
  pkg/controllers/gateway/v1alpha2/tlsroute_controller.go
  pkg/controllers/gateway/v1alpha2/udproute_controller.go
Labels: bug

#437 build(deps): bump pipy from 1.5.3 to 1.5.4
  charts/fsm/README.md
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  dockerfiles/Dockerfile.fsm-gateway
  dockerfiles/Dockerfile.fsm-ingress
  docs/tests/gateway-api/README.md
  pkg/apis/config/v1alpha3/mesh_config.go
  tests/e2e/e2e_fsm_ingress_test.go
  tests/e2e/e2e_gatewayapi_test.go
Labels: enhancement

#438 [backport] build(deps): bump pipy from 1.5.3 to 1.5.4 (#437)
  charts/fsm/README.md
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  dockerfiles/Dockerfile.fsm-gateway
  dockerfiles/Dockerfile.fsm-ingress
  docs/tests/gateway-api/README.md
  pkg/apis/config/v1alpha3/mesh_config.go
  tests/e2e/e2e_fsm_ingress_test.go
  tests/e2e/e2e_gatewayapi_test.go
Labels: enhancement

#439 build(deps): bump pipy from 1.5.4 to 1.5.5
  charts/fsm/README.md
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  dockerfiles/Dockerfile.fsm-gateway
  dockerfiles/Dockerfile.fsm-ingress
  docs/tests/gateway-api/README.md
  pkg/apis/config/v1alpha3/mesh_config.go
  tests/e2e/e2e_fsm_ingress_test.go
  tests/e2e/e2e_gatewayapi_test.go
Labels: enhancement, dependencies

#441 ci: free space before running test cases
  .github/workflows/main.yml
Labels: enhancement, github_actions

#442 [backport] ci: free space before running test cases (#441)
  .github/workflows/main.yml
Labels: enhancement, github_actions

#444 [backport] build(deps): Bump codecov/codecov-action from 4 to 5 (#443)
  .github/workflows/main.yml
Labels: enhancement, github_actions

#445 ci: switch to goreleaser for publishing release
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yaml
  Makefile
Labels: github_actions

#446 [cherry-pick] ci: switch to goreleaser for publishing release (#445)
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yaml
  Makefile
Labels: github_actions

#448 feat: generate and publish a homebrew-tap recipe for fsm cli
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: enhancement, github_actions

#449 fix: go build ldflags
  .goreleaser.yaml
Labels: bug, github_actions

#450 [cherry-pick] feat: generate and publish a homebrew-tap recipe for fsm cli
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: enhancement, github_actions

#453 fix: BUILDPLATFORM of final image
  dockerfiles/Dockerfile.fsm-bootstrap
  dockerfiles/Dockerfile.fsm-connector
  dockerfiles/Dockerfile.fsm-controller
  dockerfiles/Dockerfile.fsm-crds
  dockerfiles/Dockerfile.fsm-curl
  dockerfiles/Dockerfile.fsm-gateway
  dockerfiles/Dockerfile.fsm-healthcheck
  dockerfiles/Dockerfile.fsm-ingress
  dockerfiles/Dockerfile.fsm-injector
  dockerfiles/Dockerfile.fsm-preinstall
  dockerfiles/Dockerfile.fsm-sidecar-init
  dockerfiles/Dockerfile.fsm-xnetmgmt
  dockerfiles/Dockerfile.pipy-debian
  dockerfiles/Dockerfile.pipy-nonroot
Labels: bug

#454 feat: gateway backends support IPv6 addresses
  pkg/gateway/utils/endpointslices.go
Labels: enhancement

#455 fix: FLB support IPv6 external address
  pkg/controllers/flb/utils.go
Labels: enhancement

#459 [cherry-pick] fix: support IPv6 external address
  pkg/controllers/flb/utils.go
Labels: enhancement

#460 [cherry-pick] fix: support IPv6 external address
  pkg/controllers/flb/utils.go
Labels: enhancement

#461 [cherry-pick] fix: support IPv6 external address
  pkg/controllers/flb/utils.go
Labels: enhancement

#462 [backport] build(deps): Bump crazy-max/ghaction-docker-meta from 5.5.1 to 5.6.1.
  .github/workflows/build-pipy-nonroot.yml
  .github/workflows/release.yml
Labels: enhancement, github_actions

#458 [backport] feat: gateway backends support IPv6 addresses (#454)
  pkg/gateway/utils/endpointslices.go
Labels: enhancement

#464 feat: skip upload brew formula if no PAT
  .goreleaser.yaml
Labels: enhancement, github_actions

#465 [cherry-pick] feat: skip upload brew formula if no PAT (#464)
  .goreleaser.yaml
Labels: enhancement, github_actions

#467 fix local dns proxy.
  cmd/fsm-controller/fsm-controller.go
  pkg/dns/handler.go
  pkg/dns/resolver.go
  pkg/dns/server.go
  pkg/k8s/client.go
  pkg/k8s/mock_controller_generated.go
  pkg/k8s/types.go
  pkg/sidecar/providers/pipy/driver/pipy_container.go
  pkg/sidecar/providers/pipy/repo/jobs.go
Labels: enhancement

#468 [cherry-pick] fix local dns proxy. (#467)
  cmd/fsm-controller/fsm-controller.go
  pkg/dns/handler.go
  pkg/dns/resolver.go
  pkg/dns/server.go
  pkg/k8s/client.go
  pkg/k8s/mock_controller_generated.go
  pkg/k8s/types.go
  pkg/sidecar/providers/pipy/driver/pipy_container.go
  pkg/sidecar/providers/pipy/repo/jobs.go
Labels: enhancement

#469 feat: support new app protocols
  pkg/constants/constants.go
  pkg/gateway/processor/v2/utils.go
  pkg/gateway/status/routes/grpcroute.go
  pkg/gateway/status/routes/httproute.go
  pkg/gateway/status/routes/methods.go
  pkg/gateway/status/routes/tcproute.go
  pkg/gateway/status/routes/types.go
  pkg/gateway/status/routes/udproute.go
  pkg/gateway/status/routes/utils.go
Labels: enhancement

#472 ci: add pr-title-checker action
  .github/pr-title-checker-config.json
  .github/workflows/pr-title-check.yml
Labels: enhancement, github_actions

#475 ci: add dco action
  .github/workflows/dco.yml
Labels: enhancement, github_actions

#477 [backport] ci: add pr-title-checker action (#472)
  .github/pr-title-checker-config.json
  .github/workflows/pr-title-check.yml
Labels: enhancement, github_actions

#478 ci: add dco action (#475)[backport]
  .github/workflows/dco.yml
Labels: enhancement, github_actions

#479 ci: adjust the regex of validating PR title
  .github/pr-title-checker-config.json
  .github/workflows/pr-title-check.yml
Labels: enhancement, github_actions

#480 [BACKPORT] ci: adjust the regex of validating PR title (#479)
  .github/pr-title-checker-config.json
  .github/workflows/pr-title-check.yml
Labels: enhancement, github_actions

#484 ci: exclude github bot email from DCO check
  .github/workflows/dco.yml
Labels: enhancement

#486 [BACKPORT] build(deps): Bump docker/build-push-action from 6.9.0 to 6.10.0
  .github/workflows/build-pipy-nonroot.yml
  .github/workflows/release.yml
Labels: enhancement, github_actions

#488 [CHERRY-PICK] fix: local dns proxy. (#487)
  pkg/dns/handler.go
  pkg/dns/resolver.go
  pkg/dns/server.go
  pkg/sidecar/v1/providers/pipy/driver/pipy_container.go
Labels: enhancement

#489 ci: automatically cherry-pick/backport PR
  .github/pr-title-checker-config.json
  .github/workflows/backport.yml
  .github/workflows/cherry-pick.yml
Labels: enhancement, github_actions

#490 fix: labels pattern of cherry-pick & backport workflow
  .github/workflows/backport.yml
  .github/workflows/cherry-pick.yml
Labels: bug, github_actions

#491 [backport] ci: automatically cherry-pick/backport PR (#489)
  .github/pr-title-checker-config.json
  .github/workflows/backport.yml
  .github/workflows/cherry-pick.yml
Labels: enhancement, github_actions, title needs formatting

#492 [backport] fix: labels pattern of cherry-pick & backport workflow (#490)
  .github/workflows/backport.yml
  .github/workflows/cherry-pick.yml
Labels: bug, github_actions

#493 feat: add names for workflow
  .github/workflows/backport.yml
  .github/workflows/cherry-pick.yml
Labels: enhancement, github_actions
