Repository flomesh-io/fsm, pull requests merged in 2025-01, with the labels that each got.

#606 ci(Mergify): copy PRs those merged into main to release/v1.5
  .mergify.yml
Labels: area/CI, change/github-actions, kind/enhancement, priority/P1, size/XS, squash, backport/v1.4, ok-to-merge, copy/v1.5

#612 fix: via gateway for vm
  pkg/k8s/client.go
  pkg/sidecar/providers/pipy/repo/util.go
Labels: area/connector, change/go, kind/bug, priority/P1, size/XS, squash, ok-to-merge

#613 fix: via gateway for vm
  pkg/k8s/client.go
  pkg/sidecar/v1/providers/pipy/repo/util.go
Labels: area/connector, change/go, kind/bug, priority/P1, size/XS, squash, ok-to-merge

#614 test: use k3d to replace kind for provisioning k8s cluster
  .github/workflows/main.yml
  .mergify.yml
  Makefile
  charts/fsm/templates/fsm-deployment.yaml
  charts/fsm/templates/fsm-ingress-deployment.yaml
  charts/fsm/templates/fsm-injector-deployment.yaml
  charts/fsm/templates/fsm-xnetwork.yaml
  go.mod
  go.sum
  scripts/k3d-with-registry.sh
  tests/e2e/README.md
  tests/e2e/e2e_fsm_ingress_test.go
  tests/e2e/e2e_gatewayapi_test.go
  tests/e2e/e2e_namespacedingress_test.go
  tests/e2e/e2e_upgrade_test.go
  tests/framework/common.go
  tests/framework/common_apps.go
  tests/framework/constants.go
  tests/framework/helm.go
  tests/framework/k3d-cluster.yaml
  tests/framework/types.go
Labels: area/CI, change/dependencies, change/github-actions, change/go, kind/enhancement, priority/P1, size/S, squash, ok-to-merge

#578 test: add e2e testcases for Gateway with NodeLevel sidecar
  .github/workflows/main.yml
  .mergify.yml
  tests/e2e/e2e_fsm_ingress_test.go
  tests/e2e/e2e_fsm_reinstall_test.go
  tests/e2e/e2e_gatewayapi_test.go
  tests/e2e/e2e_namespacedingress_test.go
  tests/framework/common.go
  tests/framework/common_apps.go
  tests/framework/types.go
Labels: area/gateway-api, change/github-actions, change/go, kind/enhancement, priority/P1, size/S, squash, ok-to-merge

#621 ci: optimize e2e test workflow
  .github/workflows/main.yml
  .mergify.yml
  tests/framework/common.go
Labels: area/CI, change/github-actions, kind/enhancement, priority/P1, size/XS, squash, ok-to-merge

#622 feat: slow starting warm-up feature
  charts/fsm/README.md
  charts/fsm/templates/fsm-rbac.yaml
  charts/fsm/templates/preset-mesh-config.yaml
  charts/fsm/values.schema.json
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  cmd/fsm-bootstrap/crds/policy.flomesh.io_trafficwarmups.yaml
  pkg/announcements/types.go
  pkg/apis/config/v1alpha3/mesh_config.go
  pkg/apis/config/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/policy/v1alpha1/traffic_warmup.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/policy/v1alpha1/zz_generated.register.go
  pkg/catalog/mock_catalog_generated.go
  pkg/catalog/trafficwarmup.go
  pkg/catalog/types.go
  pkg/constants/constants.go
  pkg/gen/client/policy/clientset/versioned/typed/policy/v1alpha1/fake/fake_policy_client.go
  pkg/gen/client/policy/clientset/versioned/typed/policy/v1alpha1/fake/fake_trafficwarmup.go
  pkg/gen/client/policy/clientset/versioned/typed/policy/v1alpha1/generated_expansion.go
  pkg/gen/client/policy/clientset/versioned/typed/policy/v1alpha1/policy_client.go
  pkg/gen/client/policy/clientset/versioned/typed/policy/v1alpha1/trafficwarmup.go
  pkg/gen/client/policy/informers/externalversions/generic.go
  pkg/gen/client/policy/informers/externalversions/policy/v1alpha1/interface.go
  pkg/gen/client/policy/informers/externalversions/policy/v1alpha1/trafficwarmup.go
  pkg/gen/client/policy/listers/policy/v1alpha1/expansion_generated.go
  pkg/gen/client/policy/listers/policy/v1alpha1/trafficwarmup.go
  pkg/k8s/informers/informers.go
  pkg/k8s/informers/types.go
  pkg/messaging/broker.go
  pkg/policy/client.go
  pkg/policy/mock_client_generated.go
  pkg/policy/types.go
  pkg/sidecar/v1/providers/pipy/repo/jobs.go
  pkg/sidecar/v1/providers/pipy/repo/policy.go
Labels: area/service-mesh, change/configuration, change/go, change/helm-chart, kind/enhancement, priority/P1, size/M, squash, ok-to-merge

#623 refactor: ignore mesh services without ready endpoints.
  pkg/catalog/outbound_traffic_policies.go
Labels: area/service-mesh, change/go, kind/enhancement, priority/P1, size/XS, squash, ok-to-merge

#628 build(deps): bump fgw to 1.5.3
  charts/fsm/components/scripts.tar.gz
  charts/fsm/components/scripts/gateways/filters/http/ExternalRateLimit.js
  charts/fsm/components/scripts/gateways/filters/http/RateLimit.js
  charts/fsm/components/scripts/gateways/filters/http/RequestTermination.js
Labels: area/gateway-api, change/pjs, kind/enhancement, priority/P1, size/XS, squash, ok-to-merge

#633 fix: throttleHost is not array in ExternalRateLimit
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_externalratelimits.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_requestterminations.yaml
  pkg/apis/extension/v1alpha1/externalratelimit.go
  pkg/apis/extension/v1alpha1/requesttermination.go
  pkg/apis/extension/v1alpha1/zz_generated.deepcopy.go
Labels: area/gateway-api, change/go, kind/bug, priority/P1, size/XS, squash, ok-to-merge

#634 build(deps): bump sigs.k8s.io/controller-tools from v0.16.5 to v0.17.1
  Makefile
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshrootcertificates.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_consulconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_eurekaconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_gatewayconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_machineconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_nacosconnectors.yaml
  cmd/fsm-bootstrap/crds/connector.flomesh.io_zookeeperconnectors.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_circuitbreakers.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_concurrencylimits.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_externalratelimits.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_faultinjections.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_filterconfigs.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_filterdefinitions.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_filters.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_httplogs.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_iprestrictions.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_listenerfilters.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_metrics.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_proxytags.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_ratelimits.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_requestterminations.yaml
  cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_zipkins.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_backendlbpolicies.yaml
  cmd/fsm-bootstrap/crds/gateway.flomesh.io_healthcheckpolicies.yaml
  cmd/fsm-bootstrap/crds/machine.flomesh.io_virtualmachines.yaml
  cmd/fsm-bootstrap/crds/multicluster.flomesh.io_clusters.yaml
  cmd/fsm-bootstrap/crds/multicluster.flomesh.io_globaltrafficpolicies.yaml
  cmd/fsm-bootstrap/crds/multicluster.flomesh.io_serviceexports.yaml
  cmd/fsm-bootstrap/crds/multicluster.flomesh.io_serviceimports.yaml
  cmd/fsm-bootstrap/crds/networking.flomesh.io_namespacedingresses.yaml
  cmd/fsm-bootstrap/crds/plugin.flomesh.io_pluginchains.yaml
  cmd/fsm-bootstrap/crds/plugin.flomesh.io_pluginconfigs.yaml
  cmd/fsm-bootstrap/crds/plugin.flomesh.io_plugins.yaml
  cmd/fsm-bootstrap/crds/policy.flomesh.io_accesscerts.yaml
  cmd/fsm-bootstrap/crds/policy.flomesh.io_accesscontrols.yaml
  cmd/fsm-bootstrap/crds/policy.flomesh.io_egresses.yaml
  cmd/fsm-bootstrap/crds/policy.flomesh.io_egressgateways.yaml
  cmd/fsm-bootstrap/crds/policy.flomesh.io_ingressbackends.yaml
  cmd/fsm-bootstrap/crds/policy.flomesh.io_isolations.yaml
  cmd/fsm-bootstrap/crds/policy.flomesh.io_retries.yaml
  cmd/fsm-bootstrap/crds/policy.flomesh.io_trafficwarmups.yaml
  cmd/fsm-bootstrap/crds/policy.flomesh.io_upstreamtrafficsettings.yaml
  cmd/fsm-bootstrap/crds/traffic.flomesh.io_httptrafficrules.yaml
  cmd/fsm-bootstrap/crds/traffic.flomesh.io_trafficsplits.yaml
  cmd/fsm-bootstrap/crds/xnetwork.flomesh.io_accesscontrols.yaml
Labels: area/control-plane, change/dependencies, kind/enhancement, priority/P1, size/XS, squash, ok-to-merge

#635 build(deps): bump github.com/docker/docker from v27.2.1+incompatible to v27.5.0+incompatible
  go.mod
  go.sum
Labels: area/control-plane, change/dependencies, kind/enhancement, priority/P1, size/XS, squash, ok-to-merge

#639 test: grab logs of k3d cluster
  scripts/get-k3d-logs.sh
  tests/framework/common.go
Labels: change/go, change/shell, kind/enhancement, priority/P1, size/S, squash, ok-to-merge, area/test

#640 docs: add more approaches of getting FSM CLI
  README.md
Labels: area/documentation, kind/enhancement, priority/P2, size/XS, backport/v1.4, change/doc

#646 build(deps): bump pipy from 1.5.8 to 1.5.9
  charts/fsm/README.md
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  dockerfiles/Dockerfile.fsm-gateway
  dockerfiles/Dockerfile.fsm-ingress
  docs/tests/gateway-api/README.md
  pkg/apis/config/v1alpha3/mesh_config.go
  tests/e2e/e2e_fsm_ingress_test.go
  tests/e2e/e2e_gatewayapi_test.go
Labels: area/control-plane, change/dependencies, kind/enhancement, priority/P1, size/S, squash, backport/v1.4, ok-to-merge

#648 build(deps): bump pipy from 1.5.8 to 1.5.9(release/v1.4)
  charts/fsm/README.md
  charts/fsm/values.yaml
  cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
  dockerfiles/Dockerfile.fsm-gateway
  dockerfiles/Dockerfile.fsm-ingress
  docs/tests/gateway-api/README.md
  pkg/apis/config/v1alpha3/mesh_config.go
  tests/e2e/e2e_fsm_ingress_test.go
  tests/e2e/e2e_gatewayapi_test.go
Labels: area/control-plane, change/dependencies, kind/enhancement, priority/P2, size/XS, squash, ok-to-merge

#649 fix: nil pointer and lifecycle scripts.
  pkg/messaging/broker.go
  pkg/sidecar/v1/providers/pipy/driver/pipy_container.go
Labels: area/service-mesh, change/go, kind/bug, priority/P0, size/S, squash, ok-to-merge

#659 build(deps): bump sigs.k8s.io/controller-runtime from 0.19.4 to 0.19.5
  go.mod
  go.sum
Labels: area/control-plane, change/dependencies, kind/enhancement, priority/P1, size/XS, squash, ok-to-merge
