Repository flomesh-io/fsm, pull requests merged in 2025-08, with the labels that each got.

#1017 fix: the connection to nacos is not properly closed.
  pkg/connector/provider/nacos.go
Labels: area/connector, change/go, kind/bug, priority/P0, size/S, cherry-pick/main

#1036 fix(security): Helm issue
  Makefile
  go.mod
  go.sum
Labels: area/control-plane, change/dependencies, kind/enhancement, priority/P0, size/XS, backport/v1.5

#1047 feat: bump golang from 1.24 to 1.25
  .github/workflows/e2e.yml
  .github/workflows/main.yml
  .github/workflows/release-image.yml
  .github/workflows/release.yml
  Dockerfile
  Makefile
  cmd/fsm-gateway/fsm-gateway.go
  cmd/fsm-healthcheck/fsm-healthcheck.go
  go.mod
  go.sum
Labels: area/control-plane, change/dependencies, kind/enhancement, priority/P2, size/S
